# Generated by Django 6.0.3 on 2026-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Основной номер телефона', max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Контактный email', max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, help_text='Адрес офиса', null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Ссылка на Facebook', null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, help_text='Ссылка на Instagram', null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, help_text='Ссылка на YouTube', null=True, verbose_name='YouTube')),
                ('telegram', models.URLField(blank=True, help_text='Ссылка на Telegram', null=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, help_text='Ссылка на WhatsApp', null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки соцсетей',
            },
        ),
    ]
