# Generated by Django 6.0.3 on 2026-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Primary phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Office address', null=True)),
            ],
            options={
                'verbose_name': 'Contact Details',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube URL', null=True)),
                ('telegram', models.URLField(blank=True, help_text='Telegram URL', null=True)),
                ('whatsapp', models.URLField(blank=True, help_text='WhatsApp URL', null=True)),
            ],
            options={
                'verbose_name': 'Social Media',
            },
        ),
    ]
