# Generated by Django 6.0.3 on 2026-04-10 14:44

import cms.models.settings
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Текст, который отображается перед полями формы', verbose_name='Вступление')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Сообщение, которое увидит пользователь после успешной заполнения формы', verbose_name='Текст после отправки')),
            ],
            options={
                'verbose_name': 'Страница с формой',
                'verbose_name_plural': 'Страницы с формами',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Настройки навигации',
            },
            bases=(cms.models.settings.SettingsPreviewMixin, wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='youtube',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('services', 13), ('features', 19), ('about', 25), ('content', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Уникальный идентификатор для перехода по ссылке (например, 'services')", 'label': 'Якорь (ID)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок баннера', 'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Подзаголовок', 'label': 'Подзаголовок', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фоновое изображение', 'label': 'Изображение', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Рассчитать стоимость', 'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу, на которую ведет кнопка', 'label': 'Целевая страница', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('subtitle', 2), ('image', 3), ('cta_text', 4), ('cta_page', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Наши услуги', 'label': 'Заголовок', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('description', 9), ('image', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Список услуг'}), 13: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 7), ('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок преимущества', 'required': True}), 16: ('wagtail.blocks.TextBlock', (), {'label': 'Текст преимущества', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('title', 15), ('text', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Преимущества'}), 19: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 14), ('items', 18)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Значение (напр. 10+)', 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись (напр. лет опыта)', 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('value', 21), ('label', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Показатели/Статистика', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 14), ('content', 20), ('image', 10), ('stats', 24)]], {}), 26: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое'}), 27: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('content', 26)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='cms.formpage')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('link_url', models.CharField(blank=True, help_text='Используйте для внешних ссылок или якорей (например, #services)', max_length=500, verbose_name='Внешняя ссылка или якорь')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Ссылка на страницу')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.navigationsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'VK'), ('viber', 'Viber'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Платформа')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='cms.socialmediasettings')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
