# Generated by Django 6.0.3 on 2026-04-10 13:16

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Текст, который отображается перед полями формы', verbose_name='Вступление')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Сообщение, которое увидит пользователь после успешной заполнения формы', verbose_name='Текст после отправки')),
            ],
            options={
                'verbose_name': 'Страница с формой',
                'verbose_name_plural': 'Страницы с формами',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('services', 11), ('features', 17), ('about', 23), ('content', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок баннера', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Подзаголовок', 'label': 'Подзаголовок', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фоновое изображение', 'label': 'Изображение', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Рассчитать стоимость', 'label': 'Текст кнопки', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 3)]], {'label': 'Главный баннер', 'template': 'cms/home/blocks/hero.html'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Наши услуги', 'label': 'Заголовок', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 6), ('description', 7), ('image', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список услуг'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {'label': 'Блок услуг', 'template': 'cms/home/blocks/services.html'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок преимущества', 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'label': 'Текст преимущества', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('text', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Преимущества'}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('items', 16)]], {'label': 'Преимущества', 'template': 'cms/home/blocks/features.html'}), 18: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Значение (напр. 10+)', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись (напр. лет опыта)', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('value', 19), ('label', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'label': 'Показатели/Статистика', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 12), ('content', 18), ('image', 8), ('stats', 22)]], {'label': 'О нас', 'template': 'cms/home/blocks/about.html'}), 24: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'template': 'cms/home/blocks/rich_text.html'})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='cms.formpage')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
            },
        ),
    ]
