# Generated by Django 6.0.3 on 2026-05-06 11:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_navigationsettings_review_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Настройки robots.txt',
            },
        ),
        migrations.CreateModel(
            name='RobotsDisallowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('path', models.CharField(help_text='Например: /admin/ или /private/', max_length=500, verbose_name='Путь')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='disallow_rules', to='cms.robotssettings')),
            ],
            options={
                'verbose_name': 'Запрещённый путь',
                'verbose_name_plural': 'Запрещённые пути',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
