# Generated by Django 6.0.3 on 2026-04-10 14:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_formpage_navigationsettings_alter_homepage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('services', 13), ('features', 19), ('about', 25), ('reviews', 29), ('faq', 35), ('content', 37)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Уникальный идентификатор для перехода по ссылке (например, 'services')", 'label': 'Якорь (ID)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок баннера', 'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Подзаголовок', 'label': 'Подзаголовок', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фоновое изображение', 'label': 'Изображение', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Рассчитать стоимость', 'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу, на которую ведет кнопка', 'label': 'Целевая страница', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('subtitle', 2), ('image', 3), ('cta_text', 4), ('cta_page', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Наши услуги', 'label': 'Заголовок', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('description', 9), ('image', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Список услуг'}), 13: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 7), ('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок преимущества', 'required': True}), 16: ('wagtail.blocks.TextBlock', (), {'label': 'Текст преимущества', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('title', 15), ('text', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Преимущества'}), 19: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 14), ('items', 18)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Значение (напр. 10+)', 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись (напр. лет опыта)', 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('value', 21), ('label', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Показатели/Статистика', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 14), ('content', 20), ('image', 10), ('stats', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Отзывы наших клиентов', 'label': 'Заголовок', 'required': True}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms.Review',), {}), 28: ('wagtail.blocks.ListBlock', (27,), {'help_text': 'Выберите отзывы для отображения', 'label': 'Отзывы'}), 29: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 26), ('reviews', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Часто задаваемые вопросы', 'label': 'Заголовок', 'required': True}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'required': True}), 32: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('question', 31), ('answer', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {'label': 'Список вопросов'}), 35: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 30), ('items', 34)]], {}), 36: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое'}), 37: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('content', 36)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Рейтинг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено (показывать)')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
