# Generated by Django 6.0.3 on 2026-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_robotssettings_robotsdisallowrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accept_privacy',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено (показывать)'),
        ),
    ]
