# Generated by Django 6.0.3 on 2026-05-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_contactsettings_legal_address_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umami_website_id', models.CharField(blank=True, help_text='Уникальный идентификатор вашего сайта в Umami', max_length=255, null=True, verbose_name='Umami Website ID')),
                ('umami_server_url', models.URLField(blank=True, help_text='URL вашего сервера Umami (например, https://stats.example.com). Если оставить пустым, будет использоваться прокси /stats по умолчанию.', null=True, verbose_name='URL сервера Umami')),
                ('custom_script', models.TextField(blank=True, help_text='Вставьте сюда любой дополнительный код отслеживания (например, Google Analytics, Яндекс.Метрика)', null=True, verbose_name='Пользовательский скрипт аналитики')),
                ('site', models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки аналитики',
            },
        ),
    ]
