# Generated by Django 6.0.3 on 2026-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='legal_address',
            field=models.TextField(blank=True, help_text='Адрес регистрации', null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='legal_full_name',
            field=models.CharField(blank=True, help_text='Полное ФИО индивидуального предпринимателя', max_length=255, null=True, verbose_name='Юридическое ФИО'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='legal_reg_date',
            field=models.DateField(blank=True, help_text='Дата государственной регистрации', null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='legal_unp',
            field=models.CharField(blank=True, help_text='Учетный номер плательщика', max_length=50, null=True, verbose_name='УНП'),
        ),
    ]
