# Generated by Django 6.0.3 on 2026-05-28 13:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_analyticssettings'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_robots', models.CharField(blank=True, choices=[('index, follow', 'Индексировать, переходить по ссылкам (Index, Follow)'), ('noindex, follow', 'Не индексировать, переходить по ссылкам (Noindex, Follow)'), ('index, nofollow', 'Индексировать, не переходить по ссылкам (Index, Nofollow)'), ('noindex, nofollow', 'Не индексировать, не переходить по ссылкам (Noindex, Nofollow)')], help_text='Управление тем, как поисковые системы индексируют эту страницу', max_length=20, null=True, verbose_name='Тег Robots')),
                ('og_type', models.CharField(choices=[('website', 'Веб-сайт (Website)'), ('article', 'Статья (Article)'), ('product', 'Товар (Product)'), ('profile', 'Профиль (Profile)'), ('video.other', 'Видео (Video)')], default='website', help_text='Тип объекта в Open Graph (website, article и т.д.)', max_length=20, verbose_name='Тип Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='Если оставить пустым, будет использован текущий URL страницы. Используйте, если контент дублируется на другой странице.', null=True, verbose_name='Канонический URL')),
                ('published_date', models.DateTimeField(blank=True, help_text='Дата и время публикации страницы для поисковых систем (Open Graph)', null=True, verbose_name='Дата публикации')),
                ('modified_date', models.DateTimeField(blank=True, help_text='Дата и время последнего изменения страницы для поисковых систем (Open Graph). Если не указано, будет использовано системное время изменения.', null=True, verbose_name='Дата изменения')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Текст перед списком работ', verbose_name='Описание')),
                ('og_image', models.ForeignKey(blank=True, help_text='Загрузите кастомное изображение OG для соцсетей. Рекомендуемый размер: 1200x630px. Если не указано, будет использовано изображение родительской страницы или логотип сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение Open Graph')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'verbose_name_plural': 'Наши работы',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioWorkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_robots', models.CharField(blank=True, choices=[('index, follow', 'Индексировать, переходить по ссылкам (Index, Follow)'), ('noindex, follow', 'Не индексировать, переходить по ссылкам (Noindex, Follow)'), ('index, nofollow', 'Индексировать, не переходить по ссылкам (Index, Nofollow)'), ('noindex, nofollow', 'Не индексировать, не переходить по ссылкам (Noindex, Nofollow)')], help_text='Управление тем, как поисковые системы индексируют эту страницу', max_length=20, null=True, verbose_name='Тег Robots')),
                ('og_type', models.CharField(choices=[('website', 'Веб-сайт (Website)'), ('article', 'Статья (Article)'), ('product', 'Товар (Product)'), ('profile', 'Профиль (Profile)'), ('video.other', 'Видео (Video)')], default='website', help_text='Тип объекта в Open Graph (website, article и т.д.)', max_length=20, verbose_name='Тип Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='Если оставить пустым, будет использован текущий URL страницы. Используйте, если контент дублируется на другой странице.', null=True, verbose_name='Канонический URL')),
                ('published_date', models.DateTimeField(blank=True, help_text='Дата и время публикации страницы для поисковых систем (Open Graph)', null=True, verbose_name='Дата публикации')),
                ('modified_date', models.DateTimeField(blank=True, help_text='Дата и время последнего изменения страницы для поисковых систем (Open Graph). Если не указано, будет использовано системное время изменения.', null=True, verbose_name='Дата изменения')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание (для карточки)')),
                ('full_description', wagtail.fields.RichTextField(blank=True, verbose_name='Полное описание')),
                ('body', wagtail.fields.StreamField([('image', 2), ('text', 3), ('comparison', 7), ('gallery', 9)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('cms.blocks.portfolio.blocks.PortfolioRichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение ДО'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение ПОСЛЕ'}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image_before', 4), ('image_after', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (2,), {'label': 'Галерея'}), 9: ('wagtail.blocks.StructBlock', [[('images', 8)]], {})}, null=True, verbose_name='Контент страницы')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Основное изображение')),
                ('og_image', models.ForeignKey(blank=True, help_text='Загрузите кастомное изображение OG для соцсетей. Рекомендуемый размер: 1200x630px. Если не указано, будет использовано изображение родительской страницы или логотип сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение Open Graph')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
