# Generated by Django 6.0.3 on 2026-05-14 17:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_contactsettings_legal_address_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='legal_index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Главная юридическая страница'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='privacy_policy_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Страница политики конфиденциальности'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='terms_of_service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Страница пользовательского соглашения'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('phonenumber', 'Номер телефона'), ('checkbox_agreement', 'Чекбокс согласия')], max_length=32, verbose_name='field type'),
        ),
        migrations.CreateModel(
            name='LegalDocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_robots', models.CharField(blank=True, choices=[('index, follow', 'Индексировать, переходить по ссылкам (Index, Follow)'), ('noindex, follow', 'Не индексировать, переходить по ссылкам (Noindex, Follow)'), ('index, nofollow', 'Индексировать, не переходить по ссылкам (Index, Nofollow)'), ('noindex, nofollow', 'Не индексировать, не переходить по ссылкам (Noindex, Nofollow)')], help_text='Управление тем, как поисковые системы индексируют эту страницу', max_length=20, null=True, verbose_name='Тег Robots')),
                ('og_type', models.CharField(choices=[('website', 'Веб-сайт (Website)'), ('article', 'Статья (Article)'), ('product', 'Товар (Product)'), ('profile', 'Профиль (Profile)'), ('video.other', 'Видео (Video)')], default='website', help_text='Тип объекта в Open Graph (website, article и т.д.)', max_length=20, verbose_name='Тип Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='Если оставить пустым, будет использован текущий URL страницы. Используйте, если контент дублируется на другой странице.', null=True, verbose_name='Канонический URL')),
                ('published_date', models.DateTimeField(blank=True, help_text='Дата и время публикации страницы для поисковых систем (Open Graph)', null=True, verbose_name='Дата публикации')),
                ('modified_date', models.DateTimeField(blank=True, help_text='Дата и время последнего изменения страницы для поисковых систем (Open Graph). Если не указано, будет использовано системное время изменения.', null=True, verbose_name='Дата изменения')),
                ('body', wagtail.fields.RichTextField(help_text='Основной текст юридического документа', verbose_name='Содержание страницы')),
                ('og_image', models.ForeignKey(blank=True, help_text='Загрузите кастомное изображение OG для соцсетей. Рекомендуемый размер: 1200x630px. Если не указано, будет использовано изображение родительской страницы или логотип сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение Open Graph')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='LegalIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_robots', models.CharField(blank=True, choices=[('index, follow', 'Индексировать, переходить по ссылкам (Index, Follow)'), ('noindex, follow', 'Не индексировать, переходить по ссылкам (Noindex, Follow)'), ('index, nofollow', 'Индексировать, не переходить по ссылкам (Index, Nofollow)'), ('noindex, nofollow', 'Не индексировать, не переходить по ссылкам (Noindex, Nofollow)')], help_text='Управление тем, как поисковые системы индексируют эту страницу', max_length=20, null=True, verbose_name='Тег Robots')),
                ('og_type', models.CharField(choices=[('website', 'Веб-сайт (Website)'), ('article', 'Статья (Article)'), ('product', 'Товар (Product)'), ('profile', 'Профиль (Profile)'), ('video.other', 'Видео (Video)')], default='website', help_text='Тип объекта в Open Graph (website, article и т.д.)', max_length=20, verbose_name='Тип Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='Если оставить пустым, будет использован текущий URL страницы. Используйте, если контент дублируется на другой странице.', null=True, verbose_name='Канонический URL')),
                ('published_date', models.DateTimeField(blank=True, help_text='Дата и время публикации страницы для поисковых систем (Open Graph)', null=True, verbose_name='Дата публикации')),
                ('modified_date', models.DateTimeField(blank=True, help_text='Дата и время последнего изменения страницы для поисковых систем (Open Graph). Если не указано, будет использовано системное время изменения.', null=True, verbose_name='Дата изменения')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Текст перед списком документов', verbose_name='Описание')),
                ('og_image', models.ForeignKey(blank=True, help_text='Загрузите кастомное изображение OG для соцсетей. Рекомендуемый размер: 1200x630px. Если не указано, будет использовано изображение родительской страницы или логотип сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение Open Graph')),
            ],
            options={
                'verbose_name': 'Список юридических документов',
                'verbose_name_plural': 'Списки юридических документов',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
