# Generated by Django 6.0.3 on 2026-06-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_homepage_body_portfolioindexpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['sort_order'], 'verbose_name': 'Поле формы', 'verbose_name_plural': 'Поля формы'},
        ),
    ]
