services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: homeservice_web
    restart: always
    volumes:
      - ../db.sqlite3:/app/db.sqlite3
      - ../media:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - ../.env
    environment:
      - PORT=8000
#    depends_on:
#      - db # В будущем если будет Postgres

  nginx:
    image: nginx:latest
    container_name: homeservice_nginx
    restart: always
    # TODO: Если вы используете другой порт на сервере, измените "80:80" на "НУЖНЫЙ_ПОРТ:80"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../media:/app/media:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web

volumes:
  static_volume:
