# Generated by Django 6.0.3 on 2026-04-05 11:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('services', 11), ('content', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок баннера', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Подзаголовок', 'label': 'Подзаголовок', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фоновое изображение', 'label': 'Изображение', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Рассчитать стоимость', 'label': 'Текст кнопки', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 3)]], {'label': 'Главный баннер', 'template': 'home/blocks/hero.html'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Наши услуги', 'label': 'Заголовок', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 6), ('description', 7), ('image', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список услуг'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {'label': 'Блок услуг', 'template': 'home/blocks/services.html'}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'template': 'home/blocks/rich_text.html'})}, null=True, verbose_name='Контент страницы'),
        ),
    ]
