# Generated by Django 6.0.3 on 2026-04-04 13:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('services', 11), ('content', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Banner title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtitle', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Order service', 'label': 'Button text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 3)]], {'template': 'home/blocks/hero.html'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 6), ('description', 7), ('image', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {'template': 'home/blocks/services.html'}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Main content', 'template': 'home/blocks/rich_text.html'})}, null=True),
        ),
    ]
