name: Deploy to Production

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd HomeCleanService
            git pull origin main
            make prod-down
            make prod-build
            make prod-up
